php artisan make:model tb_about
php artisan make:model tb_categories
php artisan make:model tb_configurations
php artisan make:model tb_contact
php artisan make:model tb_feedback
php artisan make:model tb_invoice
php artisan make:model tb_invoicedetail
php artisan make:model tb_order
php artisan make:model tb_orderdetail
php artisan make:model tb_post
php artisan make:model tb_postimage
php artisan make:model tb_posttag
php artisan make:model tb_product
php artisan make:model tb_sizes
php artisan make:model tb_slides
php artisan make:model tb_supplier
php artisan make:model tb_tag
php artisan make:model tb_user

